### ISSUE TITLE
你好，请问这个项目怎么调用 post 方式的api

### ISSUE THREAD

**Issue by huiqiulilili** [newzhn/WebOpenApi#2]
例如，我在 WebOpenApi-interface 模块写了下面的接口：
```java
@RestController
@RequestMapping("/test")
public class NameController {
    @GetMapping("/get/{name}")
    public ApiResult getNameByGetRest(@PathVariable("name") String name) {
        return ApiResult.ok("/get/{name} 接口测试成功：" + name);
    }

    @PostMapping("/post/name")
    public ApiResult getNameByPostRest(@RequestBody User user) {
        return ApiResult.ok("/post name 接口测试成功：" + user.getUserName());
    }
}
```
怎么实现远程调用 getNameByPostRest() 方法？？？？
我新建了一个SpringBoot项目，yml配置如下：
```yml
server:
  port: 8865

web-open-api:
  client:
    accessKey: 2e5a0d76d6793637d67219f1d5b9623e
    secretKey: 433e33d6d608d2dbc500302b133621b3
    gatewayHost: http://localhost:8849
```
并且测试代码如下：
```java
    @Test
    void contextLoads_post() {
        HashMap<String, Object> paramMap = new HashMap<>();
        User user = new User();
        user.setUserName("zhangsan");

        paramMap.put("user", user);
        String result = apiClientFacade.invoke("POST", "/api/test/post/name", paramMap);
        Map<String, Object> resultMap = JsonUtil.toMap(result);
        System.out.println(resultMap);
    }
  ```
![图片](https://github.com/newzhn/WebOpenApi/assets/48478957/d3beeb18-7172-4295-8545-7d9cf00c65ab)
我打断点进行调试，发现 user 对象没有接收到 zhangsan，请问我的代码哪里调用有什么问题？？？
